### ISSUE TITLE
Create page for each classroom

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [GDSC-YU/tuwaiq-classrooms#3]
Requirements:
- [x] should be responsive
- [x] mobile:  each day in a page with swipe gesture to switch between days in a horizontal manner.
- [x] show free and occupied slots on a calendar like background
- [x] color of free slots should match letter color

Figma design:
https://www.figma.com/file/C3xRUtPirmcLDFhqiJwVeH/Tuwaiq-Classrooms?node-id=22%3A275

**Comment by g9wz** [comment]
abandoned the idea
